# Generated by Django 4.0 on 2022-02-24 08:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_radiolink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_text', ckeditor.fields.RichTextField()),
                ('tags', models.CharField(blank=True, max_length=50, null=True)),
                ('Img', models.ImageField(blank=True, default='400-200.png', upload_to='')),
            ],
        ),
    ]
