# Generated by Django 4.0 on 2022-04-26 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='carousel',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
